version: '3.8'

services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce_dev
    ports:
      - "3307:3306"
    networks:
      - ecommerce-network

  clientes-service:
    build:
      context: ./clientes-service
    environment:
      - DEBUG=true
    volumes:
      - clientes-service:/app
      - clientes-logs:/app/logs
    ports:
      - "8081:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  clientes-service:
  clientes-logs: