services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ecommerce_default  # será sobrescrito por dev/uat/prod
    ports:
      - "3306:3306"  # pode ser sobrescrito em outros ambientes
    networks:
      ecommerce-network:
        ipv4_address: 172.25.0.10
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5082:80"
    depends_on:
      - db
    networks: 
      ecommerce-network:
        ipv4_address: 172.25.0.11

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=meubanco
    ports:
      - "5432:5432"
    networks: 
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks: 
      - postgres-network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  clientes-service:
    build: clientes-service
    ports:
      - "8080:8080"  # padrão, sobrescrito se necessário
    networks:
      - ecommerce-network
    volumes:
      - clientes-service:/app  # em produção pode ser removido

networks:
  ecommerce-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

  postgres-network: 
    driver: bridge

volumes:
  clientes-service:
  pgdata:
  pgadmin_data:
  phpmyadmin_data:
  db_data: