version: '3'

services:
  clientes-service:
    build: clientes-service
    ports:
      - "8080:8080"
    networks:
      - minha_rede

  estoque-service:
    build: estoque-service
    ports:
      - "8081:8081"
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge